### ISSUE TITLE
syntax highlighting missing for the below

### ISSUE THREAD

**Issue by vybs** [jimmyhchan/Dustjs.tmbundle#1]
{#socialSummary.recentComments}

  {/socialSummary.recentComments}

**Comment by jimmyhchan** [comment]
@vybs Thanks for the bug.  I've fixed it in the bundle syntax. 

please pull the latest version

**Comment by vybs** [comment]
Sure, you should encourage more of the linkedin to use this bundle ...I see some of them still use IDEs that dont even support syntax highlighting:)
